# Generated by Django 4.1.7 on 2023-03-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_coupon_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='likes',
        ),
        migrations.AlterField(
            model_name='item',
            name='audio_fragments',
            field=models.FileField(blank=True, null=True, upload_to='product/audio/%Y'),
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(upload_to='product/files/%Y'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(upload_to='product/images/%Y'),
        ),
    ]
