# Generated by Django 4.1.7 on 2023-03-28 14:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_item_likes_alter_item_audio_fragments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='audio_fragments',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='product/audio/%Y'),
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='product/files/%Y'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='product/images/%Y'),
        ),
    ]
